const ratingScale = ['1', '2', '3', '4', '5'];
const ratingCriteria = ['Biisi', 'Video/show', 'Erottuvuus'];
const songs = [
  {start: 5500, end: 7700, filename: 'songs/01_Alessandra_-_Queen_Of_Kings_Norway_Official_Music_Video_Eurovision_2023.webm', title: 'Norja - Norway 🇳🇴\nAlessandra - Queen Of Kings', number: '1'},
  {start: 5500, end: 7700, filename: 'songs/02_The_Busker_-_Dance_Our_Own_Party_Malta_Official_Music_Video_Eurovision_2023.webm', title: 'Malta - Malta 🇲🇹\nThe Busker - Dance (Our Own Party)', number: '2'},
  {start: 5500, end: 7700, filename: 'songs/03_Luke_Black_-_Samo_Mi_Se_Spava_Serbia_Official_Music_Video_Eurovision_2023.webm', title: 'Serbia - Serbia 🇷🇸\nLuke Black - Samo Mi Se Spava', number: '3'},
  {start: 5500, end: 7700, filename: 'songs/04_Sudden_Lights_-_Aij_Latvia_Official_Music_Video_Eurovision_2023.webm', title: 'Latvia - Latvia 🇱🇻\nSudden Lights - Aijā', number: '4'},
  {start: 5500, end: 7700, filename: 'songs/05_Mimicat_-_Ai_Coracao_Portugal_Official_Music_Video_Eurovision_2023.webm', title: 'Portugali - Portugal 🇵🇹\nMimicat - Ai Coração', number: '5'},
  {start: 5500, end: 7700, filename: 'songs/06_Wild_Youth_-_We_Are_One_Ireland_Official_Music_Video_Eurovision_2023.webm', title: 'Irlanti - Ireland 🇮🇪\nWild Youth - We Are One', number: '6'},
  {start: 5500, end: 7700, filename: 'songs/07_Let_3_-_Mama_Croatia_Official_Music_Video_Eurovision_2023.webm', title: 'Kroatia - Croatia 🇭🇷\nLet 3 - Mama ŠČ!', number: '7'},
  {start: 5500, end: 7700, filename: 'songs/08_Remo_Forrer_-_Watergun_Switzerland_Official_Music_Video_Eurovision_2023.webm', title: 'Sveitsi - Switzerland 🇨🇭\nRemo Forrer - Watergun', number: '8'},
  {start: 5500, end: 7700, filename: 'songs/09_Noa_Kirel_-_Unicorn_Israel_Official_Music_Video_Eurovision_2023.webm', title: 'Israel - Israel 🇮🇱\nNoa Kirel - Unicorn', number: '9'},
  {start: 5500, end: 7700, filename: 'songs/10_Pasha_Parfeni_-_Soarele_i_Luna_Moldova_Official_Music_Video_Eurovision_2023.webm', title: 'Moldova - Moldova 🇲🇩\nPasha Parfeni - Soarele şi Luna', number: '10'},
  {start: 5500, end: 7700, filename: 'songs/11_Loreen_-_Tattoo_Sweden_Official_Music_Video_Eurovision_2023.webm', title: 'Ruotsi - Sweden 🇸🇪\nLoreen - Tattoo', number: '11'},
  {start: 5500, end: 7700, filename: 'songs/12_TuralTuranX_-_Tell_Me_More_Azerbaijan_Official_Music_Video_Eurovision_2023.webm', title: 'Azerbaidžan - Azerbaijan 🇦🇿\nTuralTuranX - Tell Me More', number: '12'},
  {start: 5500, end: 7700, filename: 'songs/13_Vesna_-_My_Sister_s_Crown_Czechia_Official_Video_Eurovision_2023.webm', title: 'Tšekki - Czechia 🇨🇿\nVesna - My Sister\'s Crown', number: '13'},
  {start: 5500, end: 7700, filename: 'songs/14_Mia_Nicolai_Dion_Cooper_-_Burning_Daylight_Netherlands_Official_Video_Eurovision_2023.webm', title: 'Alankomaat - Netherlands 🇳🇱\nMia Nicolai & Dion Cooper - Burning Daylight', number: '14'},
  {start: 5500, end: 7700, filename: 'songs/15_Kaarija_-_Cha_Cha_Cha_Finland_Official_Music_Video_Eurovision_2023.webm', title: 'Suomi - Finland 🇫🇮\nKäärijä - Cha Cha Cha', number: '15'},
  {start: 5500, end: 7700, filename: 'songs/16_Reiley_-_Breaking_My_Heart_Denmark_Official_Music_Video_Eurovision_2023.webm', title: 'Tanska - Denmark 🇩🇰\nReiley - Breaking My Heart', number: '16'},
  {start: 5500, end: 7700, filename: 'songs/17_Brunette_-_Future_Lover_Armenia_Official_Music_Video_Eurovision_2023.webm', title: 'Armenia - Armenia 🇦🇲\nBrunette - Future Lover', number: '17'},
  {start: 5500, end: 7700, filename: 'songs/18_Theodor_Andrei_-_D.G.T._Off_And_On_Romania_Official_Music_Video_Eurovision_2023.webm', title: 'Romania - Romania 🇷🇴\nTheodor Andrei - D.G.T. (Off And On)', number: '18'},
  {start: 5500, end: 7700, filename: 'songs/19_Alika_-_Bridges_Estonia_Official_Music_Video_Eurovision_2023.webm', title: 'Viro - Estonia 🇪🇪\nAlika - Bridges', number: '19'},
  {start: 5500, end: 7700, filename: 'songs/20_Gustaph_-_Because_Of_You_Belgium_Official_Music_Video_Eurovision_2023.webm', title: 'Belgia - Belgium 🇧🇪\nGustaph - Because Of You', number: '20'},
  {start: 5500, end: 7700, filename: 'songs/21_Andrew_Lambrou_-_Break_A_Broken_Heart_Cyprus_Official_Music_Video_Eurovision_2023.webm', title: 'Kypros - Cyprus 🇨🇾\nAndrew Lambrou - Break A Broken Heart', number: '21'},
  {start: 5500, end: 7700, filename: 'songs/22_Dilja_-_Power_Iceland_Official_Music_Video_Eurovision_2023.webm', title: 'Islanti - Iceland 🇮🇸\nDiljá - Power', number: '22'},
  {start: 5500, end: 7700, filename: 'songs/23_Victor_Vernicos_-_What_They_Say_Greece_Official_Music_Video_Eurovision_2023.webm', title: 'Kreikka - Greece 🇬🇷\nVictor Vernicos - What They Say', number: '23'},
  {start: 5500, end: 7700, filename: 'songs/24_Blanka_-_Solo_Poland_Official_Music_Video_Eurovision_2023.webm', title: 'Puola - Poland 🇵🇱\nBlanka - Solo', number: '24'},
  {start: 5500, end: 7700, filename: 'songs/25_Joker_Out_-_Carpe_Diem_Slovenia_Official_Video_Eurovision_2023.webm', title: 'Slovenia - Slovenia 🇸🇮\nJoker Out - Carpe Diem', number: '25'},
  {start: 5500, end: 7700, filename: 'songs/26_Iru_-_Echo_Georgia_Official_Music_Video_Eurovision_2023.webm', title: 'Georgia - Georgia 🇬🇪\nIru - Echo', number: '26'},
  {start: 5500, end: 7700, filename: 'songs/27_Piqued_Jacks_-_Like_An_Animal_San_Marino_Official_Music_Video_Eurovision_2023.webm', title: 'San Marino - San Marino 🇸🇲\nPiqued Jacks - Like An Animal', number: '27'},
  {start: 5500, end: 7700, filename: 'songs/28_Teya_Salena_-_Who_The_Hell_Is_Edgar_Austria_Official_Music_Video_Eurovision_2023.webm', title: 'Itävalta - Austria 🇦🇹\nTeya & Salena - Who The Hell Is Edgar?', number: '28'},
  {start: 5500, end: 7700, filename: 'songs/29_Albina_Familja_Kelmendi_-_Duje_Albania_Official_Music_Video_Eurovision_2023.webm', title: 'Albania - Albania 🇦🇱\nAlbina & Familja Kelmendi - Duje', number: '29'},
  {start: 5500, end: 7700, filename: 'songs/30_Monika_Linkyt_-_Stay_Lithuania_Official_Music_Video_Eurovision_2023.webm', title: 'Liettua - Lithuania 🇱🇹\nMonika Linkytė - Stay', number: '30'},
  {start: 5500, end: 7700, filename: 'songs/31_Voyager_-_Promise_Australia_Official_Music_Video_Eurovision_2023.webm', title: 'Australia - Australia 🇦🇺\nVoyager - Promise', number: '31'},
  {start: 5500, end: 7700, filename: 'songs/32_La_Zarra_-_Evidemment_France_Official_Music_Video_Eurovision_2023.webm', title: 'Ranska - France 🇫🇷\nLa Zarra - Évidemment', number: '32'},
  {start: 5500, end: 7700, filename: 'songs/33_Lord_Of_The_Lost_-_Blood_Glitter_Germany_Official_Music_Video_Eurovision_2023.webm', title: 'Saksa - Germany 🇩🇪\nLord Of The Lost - Blood & Glitter', number: '33'},
  {start: 5500, end: 7700, filename: 'songs/34_Marco_Mengoni_-_Due_Vite_Italy_Official_Music_Video_Eurovision_2023.webm', title: 'Italia - Italy 🇮🇹\nMarco Mengoni - Due Vite', number: '34'},
  {start: 5500, end: 7700, filename: 'songs/35_Blanca_Paloma_-_EAEA_Spain_Official_Music_Video_Eurovision_2023.webm', title: 'Espanja - Spain 🇪🇸\nBlanca Paloma - EAEA', number: '35'},
  {start: 5500, end: 7700, filename: 'songs/36_Mae_Muller_-_I_Wrote_A_Song_United_Kingdom_Official_Music_Video_Eurovision_2023.webm', title: 'Iso-Britannia - United Kingdom 🇬🇧\nMae Muller - I Wrote A Song', number: '36'},
  {start: 5500, end: 7700, filename: 'songs/37_TVORCHI_-_Heart_Of_Steel_Eurovision_Version_Ukraine_Official_Music_Video_Eurovision_2023.webm', title: 'Ukraina - Ukraine 🇺🇦\nTVORCHI - Heart Of Steel', number: '37'},
];